# Generated by Django 2.1.7 on 2019-12-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('lname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
        ),
    ]
