# Generated by Django 2.1.7 on 2020-01-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='diabetes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[(None, 'Gender'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('total_cholestrol', models.IntegerField(blank=True, null=True)),
                ('hdl_cholestrol', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('waist', models.IntegerField(blank=True, null=True)),
                ('hip', models.IntegerField(blank=True, null=True)),
                ('physically_active', models.CharField(choices=[(None, 'Select'), ('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=100, null=True)),
                ('eat', models.CharField(choices=[(None, 'Select'), ('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=100, null=True)),
                ('bp', models.CharField(choices=[(None, 'Select'), ('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=100, null=True)),
                ('relative_diabetes', models.CharField(choices=[(None, 'Select'), ('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=100, null=True)),
                ('parent_diabetes', models.CharField(choices=[(None, 'Select'), ('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=100, null=True)),
                ('glucose', models.CharField(choices=[(None, 'Select'), ('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=100, null=True)),
                ('smoking', models.CharField(choices=[(None, 'Select'), ('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=100, null=True)),
                ('heart_disease', models.CharField(choices=[(None, 'Select'), ('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=100, null=True)),
                ('depression', models.CharField(choices=[(None, 'Select'), ('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=100, null=True)),
                ('HbA1c', models.IntegerField(blank=True, null=True)),
                ('haem', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
