# Generated by Django 2.1.7 on 2020-01-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medx', '0002_diabetes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='smoking',
            field=models.CharField(choices=[(None, 'Select'), ('Never smoked', 'Never smoked'), ('Ex-smoker', 'Ex-smoker'), ('Low-smoker(<=10/month)', 'Low-smoker(<=10/month)'), ('Mid-smoker(11-20/month)', 'Mid-smoker(11-20/month)'), ('High-smoker(>20/month)', 'High-smoker(>20/month)')], max_length=100, null=True),
        ),
    ]
