# Generated by Django 2.1.7 on 2020-01-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medx', '0003_auto_20200112_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='bp',
            field=models.CharField(choices=[(None, 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='depression',
            field=models.CharField(choices=[(None, 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='eat',
            field=models.CharField(choices=[(None, 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='gender',
            field=models.CharField(choices=[(None, 'Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='glucose',
            field=models.CharField(choices=[(None, 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='heart_disease',
            field=models.CharField(choices=[(None, 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='parent_diabetes',
            field=models.CharField(choices=[(None, 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='physically_active',
            field=models.CharField(choices=[(None, 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='relative_diabetes',
            field=models.CharField(choices=[(None, 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=100, null=True),
        ),
    ]
