# Generated by Django 2.1.7 on 2020-01-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medx', '0004_auto_20200112_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetes',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
