# Generated by Django 2.1.7 on 2020-01-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medx', '0005_diabetes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
