# Generated by Django 2.1.7 on 2020-01-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medx', '0006_auto_20200112_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
