# Generated by Django 2.1.7 on 2020-01-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medx', '0007_auto_20200112_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diabetes',
            name='slug',
        ),
    ]
