# Generated by Django 2.1.7 on 2020-01-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medx', '0008_remove_diabetes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetes',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
